#!/usr/bin/env python3
"""
MicT - Motion is the Choreographer
Continuous Motion Transition Generation
arXiv 2508.04049

Kiến trúc (arXiv 2508.04049 — chính xác theo paper):
  1. ObservationEncoder (mc encoder):
     masked_sequence m → Linear → SinPosEmbed → NL(=LayerNorm) → MHA → FFN → mc'
     NL = normalization layer (LayerNorm only, paper: "NL is the normalization layer")

  2. MicTDenoiser:
     noisy_complete n_t →
       Self-MHA →
       Cross-Attention(K=mc', V=mc') →
       FFN →
       pred p_0 (clean x0-prediction)

Noise schedule: COSINE (paper: "αt is generated by the cosine scheduler")

Loss: L_joint = MAE(pred_p0, gt_p0) trên toàn bộ valid frames (Eq. 8 trong paper)

Training masking: random 0.3 probability per frame (paper: "random mask mechanism with probability 0.3")
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional, Tuple


# ---------------------------------------------------------------------------
# Positional Encoding (sinusoidal, non-learned)
# ---------------------------------------------------------------------------

class SinPosEncoding(nn.Module):
    """
    Sinusoidal positional encoding theo Attention Is All You Need.
    Adds PE to the last dim of x: (B, T, D).
    """

    def __init__(self, hidden_dim: int, max_len: int = 512, dropout: float = 0.1):
        super().__init__()
        self.dropout = nn.Dropout(dropout)

        pe = torch.zeros(max_len, hidden_dim)                        # (max_len, D)
        pos = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)  # (max_len, 1)
        div = torch.exp(
            torch.arange(0, hidden_dim, 2).float() * (-math.log(10000.0) / hidden_dim)
        )
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div[:hidden_dim // 2])
        pe = pe.unsqueeze(0)                                          # (1, max_len, D)
        self.register_buffer('pe', pe)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: (B, T, D)
        x = x + self.pe[:, :x.size(1), :]
        return self.dropout(x)


# ---------------------------------------------------------------------------
# Sinusoidal timestep embedding (for diffusion step t)
# ---------------------------------------------------------------------------

class TimestepEmbedding(nn.Module):
    """Map scalar timestep t → embedding vector of dim `dim`."""

    def __init__(self, dim: int, max_steps: int = 1000):
        super().__init__()
        self.dim = dim

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        # t: (B,) int tensor
        device = t.device
        half = self.dim // 2
        freqs = torch.exp(
            -math.log(10000) * torch.arange(half, device=device) / (half - 1)
        )  # (half,)
        args = t.float()[:, None] * freqs[None, :]    # (B, half)
        emb = torch.cat([torch.sin(args), torch.cos(args)], dim=-1)  # (B, dim)
        if self.dim % 2 == 1:
            emb = F.pad(emb, (0, 1))                  # rare: odd dim
        return emb


# ---------------------------------------------------------------------------
# ObservationEncoder — encode masked sequence m → mc' (context)
# ---------------------------------------------------------------------------

class ObservationEncoder(nn.Module):
    """
    Encodes the masked observation sequence m (transition frames = 0)
    into a context representation mc'.

    Paper: "NL → MHA → FFN" applied to linear-projected + pos-embedded input.

    NL = Nonlinear = LayerNorm + GELU activation layer
    """

    def __init__(
        self,
        input_dim: int = 1659,
        hidden_dim: int = 512,
        num_heads: int = 8,
        num_layers: int = 4,
        ff_mult: int = 4,
        dropout: float = 0.1,
        max_len: int = 512,
    ):
        super().__init__()
        self.input_proj = nn.Linear(input_dim, hidden_dim)
        self.pos_enc    = SinPosEncoding(hidden_dim, max_len, dropout)

        # NL = normalization layer (paper: "NL is the normalization layer")
        # Chỉ LayerNorm, KHÔNG có activation function
        self.nl = nn.LayerNorm(hidden_dim)

        # Transformer encoder layers (MHA + FFN)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim * ff_mult,
            dropout=dropout,
            activation='gelu',
            batch_first=True,
            norm_first=True,   # Pre-LN for stability
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

    def forward(
        self,
        masked_seq: torch.Tensor,          # (B, T, 1659)
        padding_mask: Optional[torch.Tensor] = None,  # (B, T) True=padded
    ) -> torch.Tensor:
        """Returns mc': (B, T, hidden_dim) — Key/Value for cross-attention."""
        x = self.input_proj(masked_seq)    # (B, T, D)  Linear layer (W^m, b^m)
        x = self.pos_enc(x)                # (B, T, D)  + PE (sine function)
        x = self.nl(x)                     # (B, T, D)  NL = LayerNorm (normalization layer)
        # Then MHA → FFN (inside TransformerEncoder)
        # PyTorch TransformerEncoder: key_padding_mask — True = ignore position
        mc = self.encoder(x, src_key_padding_mask=padding_mask)  # (B, T, D) = mc'
        return mc


# ---------------------------------------------------------------------------
# DenoiserBlock — Self-Attn → Cross-Attn(mc') → FFN
# ---------------------------------------------------------------------------

class DenoiserBlock(nn.Module):
    """
    One block of the denoiser:
      x → Self-MHA → Cross-MHA(K,V=mc') → FFN
    Pre-LayerNorm (more stable training).
    """

    def __init__(self, hidden_dim: int, num_heads: int, ff_mult: int = 4, dropout: float = 0.1):
        super().__init__()
        # Self-attention
        self.norm_self  = nn.LayerNorm(hidden_dim)
        self.self_attn  = nn.MultiheadAttention(
            hidden_dim, num_heads, dropout=dropout, batch_first=True
        )

        # Cross-attention (queries from denoiser, K/V from encoder)
        self.norm_cross = nn.LayerNorm(hidden_dim)
        self.cross_attn = nn.MultiheadAttention(
            hidden_dim, num_heads, dropout=dropout, batch_first=True
        )

        # FFN
        self.norm_ff = nn.LayerNorm(hidden_dim)
        self.ff = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim * ff_mult),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim * ff_mult, hidden_dim),
            nn.Dropout(dropout),
        )

    def forward(
        self,
        x: torch.Tensor,          # (B, T, D) — noisy sequence
        mc: torch.Tensor,          # (B, T, D) — encoded context (K, V)
        self_attn_mask: Optional[torch.Tensor] = None,
        context_key_padding_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        # Self-attention (pre-norm)
        h = self.norm_self(x)
        attn_out, _ = self.self_attn(h, h, h, attn_mask=self_attn_mask)
        x = x + attn_out

        # Cross-attention: Q = x, K = V = mc
        h = self.norm_cross(x)
        cross_out, _ = self.cross_attn(
            h, mc, mc,
            key_padding_mask=context_key_padding_mask
        )
        x = x + cross_out

        # FFN (pre-norm)
        x = x + self.ff(self.norm_ff(x))
        return x


# ---------------------------------------------------------------------------
# MicTDiffusionModel — full model
# ---------------------------------------------------------------------------

class MicTDiffusionModel(nn.Module):
    """
    MicT Complete Model (arXiv 2508.04049):

    Forward pass:
        1. Encode masked observation m → mc' via ObservationEncoder
        2. Project noisy sequence n_t + timestep emb → hidden
        3. Stack of DenoiserBlock (self-attn + cross-attn(mc') + FFN)
        4. Predict clean n_0 (x0-prediction)

    Training:
        - Input: (n_t, t, masked_seq m)
        - Target: original clean sequence n_0
        - Loss: MAE on joint positions (on transition frames only)
              + MSE noise prediction on full sequence
    """

    def __init__(
        self,
        input_dim: int = 1659,
        hidden_dim: int = 512,
        num_heads: int = 8,
        enc_layers: int = 4,         # ObservationEncoder transformer layers
        dec_layers: int = 6,         # Denoiser transformer layers
        ff_mult: int = 4,
        dropout: float = 0.1,
        max_len: int = 512,
        num_timesteps: int = 1000,
    ):
        super().__init__()
        self.input_dim     = input_dim
        self.hidden_dim    = hidden_dim
        self.num_timesteps = num_timesteps

        # --- Observation Encoder (mc encoder) ---
        self.obs_encoder = ObservationEncoder(
            input_dim=input_dim,
            hidden_dim=hidden_dim,
            num_heads=num_heads,
            num_layers=enc_layers,
            ff_mult=ff_mult,
            dropout=dropout,
            max_len=max_len,
        )

        # --- Denoiser input projection ---
        self.noisy_proj  = nn.Linear(input_dim, hidden_dim)
        self.pos_enc     = SinPosEncoding(hidden_dim, max_len, dropout)

        # --- Timestep embedding → injected per-frame via broadcast addition ---
        self.time_embed  = TimestepEmbedding(hidden_dim)
        self.time_proj   = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )

        # --- Denoiser blocks ---
        self.dec_layers = nn.ModuleList([
            DenoiserBlock(hidden_dim, num_heads, ff_mult, dropout)
            for _ in range(dec_layers)
        ])
        self.out_norm = nn.LayerNorm(hidden_dim)

        # --- Output projection: predict clean x0 ---
        self.out_proj = nn.Linear(hidden_dim, input_dim)

        self._init_weights()

    def _init_weights(self):
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)

    def encode_context(
        self,
        masked_seq: torch.Tensor,             # (B, T, input_dim)
        padding_mask: Optional[torch.Tensor] = None,  # (B, T) True=pad
    ) -> torch.Tensor:
        """Encode observation sequence → mc' for KV cross-attention."""
        return self.obs_encoder(masked_seq, padding_mask)

    def denoise(
        self,
        noisy_seq: torch.Tensor,              # (B, T, input_dim) — n_t
        timesteps: torch.Tensor,              # (B,) int
        mc: torch.Tensor,                     # (B, T, hidden_dim) — encoded context
        context_key_padding_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Predict clean sequence x0 from noisy n_t and context mc'.
        Returns: (B, T, input_dim) — predicted clean sequence
        """
        B, T, _ = noisy_seq.shape

        # Project noisy input + add position encoding
        x = self.noisy_proj(noisy_seq)    # (B, T, D)
        x = self.pos_enc(x)               # (B, T, D)

        # Timestep embedding broadcast across frames
        t_emb = self.time_proj(self.time_embed(timesteps))  # (B, D)
        x = x + t_emb.unsqueeze(1)                          # (B, T, D)

        # Denoiser blocks: self-attn + cross-attn(mc') + FFN
        for block in self.dec_layers:
            x = block(x, mc, context_key_padding_mask=context_key_padding_mask)

        x = self.out_norm(x)
        pred_x0 = self.out_proj(x)         # (B, T, input_dim)
        return pred_x0

    def forward(
        self,
        noisy_seq: torch.Tensor,              # (B, T, input_dim) n_t
        timesteps: torch.Tensor,              # (B,) int diffusion step
        masked_seq: torch.Tensor,             # (B, T, input_dim) observation m
        padding_mask: Optional[torch.Tensor] = None,  # (B, T) True=padded position
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Full forward pass.
        Returns:
            pred_x0: (B, T, input_dim) — predicted clean sequence
            mc:      (B, T, hidden_dim) — encoded context (for auxiliary use)
        """
        mc = self.encode_context(masked_seq, padding_mask)
        pred_x0 = self.denoise(noisy_seq, timesteps, mc, padding_mask)
        return pred_x0, mc

    # ------------------------------------------------------------------
    # Checkpoint helpers
    # ------------------------------------------------------------------

    @property
    def config(self):
        return {
            'input_dim':     self.input_dim,
            'hidden_dim':    self.hidden_dim,
            'num_heads':     self.obs_encoder.encoder.layers[0].self_attn.num_heads,
            'enc_layers':    len(self.obs_encoder.encoder.layers),
            'dec_layers':    len(self.dec_layers),
            'num_timesteps': self.num_timesteps,
        }

    def save(self, path: str):
        torch.save({
            'model_state_dict': self.state_dict(),
            'config': self.config,
        }, path)

    @classmethod
    def load(cls, path: str, device: str = 'cpu') -> 'MicTDiffusionModel':
        ckpt = torch.load(path, map_location=device)
        cfg  = ckpt.get('config', {})
        model = cls(
            input_dim     = cfg.get('input_dim',     1659),
            hidden_dim    = cfg.get('hidden_dim',    512),
            num_heads     = cfg.get('num_heads',     8),
            enc_layers    = cfg.get('enc_layers',    4),
            dec_layers    = cfg.get('dec_layers',    6),
            num_timesteps = cfg.get('num_timesteps', 1000),
        )
        model.load_state_dict(ckpt['model_state_dict'])
        model.to(device)
        return model


# ---------------------------------------------------------------------------
# DDPM forward process (noise schedule)
# ---------------------------------------------------------------------------

class MicTDDPMScheduler:
    """
    DDPM scheduler for MicT — uses COSINE noise schedule.
    Paper: "αt is generated by the cosine scheduler of the diffusion model"
    (Improved DDPM, Nichol & Dhariwal 2021)

    Supports x0-prediction (model predicts clean motion p0 directly).
    Inference: DDPM reverse I steps, T = T-(1-i/I) per iteration.
    """

    def __init__(self, num_timesteps: int = 1000, s: float = 0.008):
        """
        Args:
            num_timesteps: total diffusion steps T
            s: offset parameter from Improved DDPM paper (default 0.008)
        """
        self.num_timesteps = num_timesteps

        # --- Cosine schedule (Improved DDPM, Eq. 17) ---
        # alpha_bar_t = cos^2( ((t/T + s) / (1 + s)) * pi/2 )
        steps = num_timesteps + 1
        t_vals = torch.linspace(0, num_timesteps, steps)  # 0 .. T
        f = torch.cos(((t_vals / num_timesteps + s) / (1 + s)) * math.pi / 2) ** 2
        alphas_cumprod = f / f[0]                          # normalize so alpha_bar_0 = 1
        alphas_cumprod = alphas_cumprod[1:]               # shape (T,): alpha_bar_1..T
        alphas_cumprod = alphas_cumprod.clamp(min=1e-5)

        # betas from cumprod: beta_t = 1 - alpha_bar_t / alpha_bar_{t-1}
        alpha_bar_prev = torch.cat([torch.ones(1), alphas_cumprod[:-1]])
        betas = (1 - alphas_cumprod / alpha_bar_prev).clamp(0, 0.999)
        alphas = 1.0 - betas

        self.register('betas',            betas)
        self.register('alphas',           alphas)
        self.register('alphas_cumprod',   alphas_cumprod)
        self.register('sqrt_alphas_cumprod',       alphas_cumprod.sqrt())
        self.register('sqrt_one_minus_alphas_cumprod', (1 - alphas_cumprod).sqrt())

    def register(self, name, tensor):
        setattr(self, name, tensor)

    def to(self, device):
        for attr in ['betas', 'alphas', 'alphas_cumprod',
                     'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod']:
            setattr(self, attr, getattr(self, attr).to(device))
        return self

    def add_noise(
        self,
        x0: torch.Tensor,     # (B, T, D) clean
        t:  torch.Tensor,     # (B,) int timestep indices
        noise: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Sample x_t ~ q(x_t | x_0). Returns (x_t, noise)."""
        if noise is None:
            noise = torch.randn_like(x0)
        sqrt_ac  = self.sqrt_alphas_cumprod[t].view(-1, 1, 1)
        sqrt_omc = self.sqrt_one_minus_alphas_cumprod[t].view(-1, 1, 1)
        x_t = sqrt_ac * x0 + sqrt_omc * noise
        return x_t, noise

    @torch.no_grad()
    def ddpm_step(
        self,
        model: MicTDiffusionModel,
        x_t: torch.Tensor,
        t_int: int,
        masked_seq: torch.Tensor,
        padding_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        One reverse DDPM step: compute x_{t-1} from x_t using model's x0 prediction.
        """
        device = x_t.device
        B = x_t.shape[0]
        t_tensor = torch.full((B,), t_int, device=device, dtype=torch.long)

        pred_x0, _ = model(x_t, t_tensor, masked_seq, padding_mask)
        pred_x0 = pred_x0.clamp(-1.5, 1.5)   # safety clamp

        if t_int == 0:
            return pred_x0

        # Compute x_{t-1} from x0 and x_t
        alpha_bar_t = self.alphas_cumprod[t_int]
        alpha_bar_prev = self.alphas_cumprod[t_int - 1]
        beta_t = self.betas[t_int]

        # Posterior mean
        coeff_x0  = (alpha_bar_prev.sqrt() * beta_t)       / (1 - alpha_bar_t)
        coeff_xt  = (self.alphas[t_int].sqrt() * (1 - alpha_bar_prev)) / (1 - alpha_bar_t)
        mean      = coeff_x0 * pred_x0 + coeff_xt * x_t

        # Posterior variance (simplified)
        var   = beta_t * (1 - alpha_bar_prev) / (1 - alpha_bar_t)
        noise = torch.randn_like(x_t) if t_int > 1 else torch.zeros_like(x_t)
        x_prev = mean + var.sqrt() * noise
        return x_prev

    @torch.no_grad()
    def sample(
        self,
        model: MicTDiffusionModel,
        masked_seq: torch.Tensor,            # (B, T, input_dim)
        num_inference_steps: int = 50,
        padding_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Full DDPM reverse sampling.
        Paper inference: T = T - (1 - i/I) per iteration.

        Returns: (B, T, input_dim) generated motion.
        """
        device = masked_seq.device
        B, T, D = masked_seq.shape
        model.eval()

        # Start from pure noise
        x_t = torch.randn(B, T, D, device=device)

        # Timestep schedule: T ... 0  (I steps, fractional decrement)
        I = num_inference_steps
        N = self.num_timesteps
        timestep_seq = [int(N - 1 - (N - 1) * i / I) for i in range(I)]

        for i, t_int in enumerate(timestep_seq):
            x_t = self.ddpm_step(model, x_t, t_int, masked_seq, padding_mask)

        return x_t
